
name: continuous-delivery
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

env:
  GOLANG_VERSION: "1.18.x"
  GOLANGCI_LINT_VERSION: "v1.47"
  KUBEBUILDER_VERSION: "2.3.1"
  KIND_VERSION: "v0.11.0"
  ROOK_VERSION: "v1.6.8"

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  duplicate_runs:
    runs-on: ubuntu-20.04
    name: Skip duplicate runs
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip == 'true' && github.ref != 'refs/heads/main' }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["README.md", "docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  change-triage:
    name: Check changed files
    needs: duplicate_runs
    if: ${{ needs.duplicate_runs.outputs.should_skip != 'true' }}
    runs-on: ubuntu-20.04
    outputs:
      docs-changed: ${{ steps.filter.outputs.docs-changed }}
      operator-changed: ${{ steps.filter.outputs.operator-changed }}
      test-changed: ${{ steps.filter.outputs.test-changed }}
      shell-script-changed: ${{ steps.filter.outputs.shell-script-changed }}
      go-code-changed: ${{ steps.filter.outputs.go-code-changed }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check for changes
      uses: dorny/paths-filter@v2.10.2
      id: filter
      # Remember to add new folders in the operator-changed filter if needed
      with:
        base: ${{ (github.event_name == 'schedule') && 'main' || '' }}
        filters: |
          docs-changed:
            - '**/*.md'
            - 'docs/**'
            - '.wordlist-en-custom.txt'
          operator-changed:
            - 'api/**'
            - 'cmd/**'
            - 'config/**'
            - 'controllers/**'
            - 'internal/**'
            - 'licenses/**'
            - 'pkg/**'
            - '.github/workflows/continuous-delivery.yml'
            - '.goreleaser-multiarch.yml'
            - 'Dockerfile'
            - 'Makefile'
            - 'go.mod'
            - 'go.sum'
          test-changed:
            - 'tests/**'
            - 'hack/**'
          shell-script-changed:
            - '**/*.sh'
          go-code-changed:
            - '**/*.go'
            - '.golangci.yml'
  golangci:
    name: Run linters
    needs:
      - duplicate_runs
      - change-triage
    # Run Go linter only if Go code has changed
    if: |
      needs.duplicate_runs.outputs.should_skip != 'true' &&
      needs.change-triage.outputs.go-code-changed == 'true'
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      -
        name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout 4m

  shellcheck:
    name: Run shellcheck linter
    needs:
      - duplicate_runs
      - change-triage
    # Run shellcheck linter if shell code has changed
    if: |
      needs.duplicate_runs.outputs.should_skip != 'true' &&
      needs.change-triage.outputs.shell-script-changed == 'true'
    runs-on: ubuntu-20.04
    env:
        SHELLCHECK_OPTS: -a -S style
    steps:
    -
      uses: actions/checkout@v3
    -
      name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0

  tests:
    name: Run unit tests
    needs:
      - duplicate_runs
      - change-triage
    # Run unit tests only if the operator or the Go codebase have changed
    if: |
      needs.duplicate_runs.outputs.should_skip != 'true' &&
      (
        needs.change-triage.outputs.operator-changed == 'true' ||
        needs.change-triage.outputs.go-code-changed == 'true'
      )
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # The Unit test is performed on multiple supported k8s versions (one
        # job for each k8s version):
        k8s-version:
          - 1.21.x
          - 1.22.x
          - 1.23.x
          - 1.24.x
          - 1.25.x
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      -
        name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Run unit tests
        env:
          ENVTEST_K8S_VERSION: ${{ matrix.k8s-version }}
        run: |
          make test
      -
        name: Coverage Summary
        if: matrix.k8s-version == '1.23.x'
        run: |
          go tool cover -func=cover.out -o coverage.out
      -
        name: Checkout EDB GitHub Actions Repo
        if: matrix.k8s-version == '1.23.x'
        uses: actions/checkout@v3
        with:
          repository: EnterpriseDB/edb-github-actions.git
          # wokeignore:rule=master
          ref: master
          token: ${{ secrets.GH_API_TOKEN }}
          path: .github/actions/edb-github-actions
      -
        name: SonarQube Scan
        if: matrix.k8s-version == '1.23.x'
        uses: ./.github/actions/edb-github-actions/sonarqube
        with:
          REPO_NAME: '${{ github.event.repository.name }}'
          SONAR_PROJECT_KEY: '${{ secrets.SONARQUBE_PROJECTKEY }}'
          SONAR_URL: '${{ secrets.SONARQUBE_URL }}'
          SONAR_LOGIN: '${{ secrets.SONARQUBE_LOGIN }}'
          PULL_REQUEST_KEY: '${{ github.event.number }}'
          PULL_REQUEST_BRANCH: '${{ github.head_ref }}'
          PULL_REQUEST_BASE_BRANCH: '${{ github.base_ref }}'
          REPO_DEFAULT_BRANCH: '${{ github.event.repository.default_branch }}'
          REPO_EXCLUDE_FILES: '**/*_test.go,**/*.md,**/*.txt,**/*.yaml,**/*.yml,**/*.template,**/*.json,**/*.csv'
      -
        name: Publish unit test summary
        if: matrix.k8s-version == '1.23.x'
        run: |
          echo "Unit test coverage: $(tail -n 1 coverage.out | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
  apidoc:
    name: Verify API doc is up to date
    needs:
      - duplicate_runs
      - change-triage
    # Run make apidoc if Go code or docs have changed
    if: |
      needs.duplicate_runs.outputs.should_skip != 'true' &&
      (
        needs.change-triage.outputs.go-code-changed == 'true' ||
        needs.change-triage.outputs.docs-changed == 'true'
      )
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    - name: Run make apidoc
      run: |
        make apidoc
    - name: Verify apidoc changes
      run: |
        apidoc_file_path='docs/src/api_reference.md'
        if git status --porcelain $apidoc_file_path | grep '^ M'; then
          echo "The API documentation doesn't reflect the current API. Please run make apidoc."
          exit 1
        fi
  crd:
    name: Verify CRD is up to date
    needs:
      - duplicate_runs
      - change-triage
    # Run make manifests if Go code have changed
    if: ${{ needs.duplicate_runs.outputs.should_skip != 'true' && needs.change-triage.outputs.go-code-changed == 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Run make manifests
        run: |
          make manifests
      - name: Check CRD manifests are up to date
        run: |
          crd_path='config/crd'
          if git status --porcelain $crd_path | grep '^ M'; then
            echo "The CRD manifests do not reflect the current API. Please run make manifests."
            exit 1
          fi
  buildx:
    name: Build containers
    needs:
      - golangci
      - shellcheck
      - tests
      - apidoc
      - crd
      - duplicate_runs
      - change-triage
    if: |
      (
        github.event_name == 'schedule' ||
        needs.duplicate_runs.outputs.should_skip != 'true' &&
        (
          needs.change-triage.outputs.operator-changed == 'true' ||
          needs.change-triage.outputs.test-changed == 'true' ||
          needs.change-triage.outputs.shell-script-changed == 'true' ||
          needs.change-triage.outputs.go-code-changed == 'true'
        )
      ) &&
      always() &&
      (needs.golangci.result == 'success' || needs.golangci.result == 'skipped') &&
      (needs.shellcheck.result == 'success' || needs.shellcheck.result == 'skipped') &&
      (needs.tests.result == 'success' || needs.tests.result == 'skipped') &&
      (needs.apidoc.result == 'success' || needs.apidoc.result == 'skipped') &&
      (needs.crd.result == 'success' || needs.crd.result == 'skipped')
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.image-meta.outputs.image }}
      cnp_version: ${{ steps.build-meta.outputs.cnp_version }}
      # 'branch_name' is used in 'GetMostRecentReleaseTag' in the Go code
      branch_name: ${{ steps.build-meta.outputs.branch_name }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          # To identify the commit we need the history and all the tags.
          fetch-depth: 0
      -
        name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      -
        name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Build meta
        id: build-meta
        run: |
          images='docker.cloudsmith.io/enterprisedb/dev_cloudnative/edb-postgres-for-kubernetes'
          tags=''
          labels=''
          commit_sha=${{ github.event.pull_request.head.sha || github.sha }}
          commit_date=$(git log -1 --pretty=format:'%ad' --date short "${commit_sha}")
          # use git describe to get the nearest tag and use that to build the version (e.g. 1.4.0+dev24 or 1.4.0)
          commit_version=$(git describe --tags --match 'v*' "${commit_sha}"| sed -e 's/^v//; s/-g[0-9a-f]\+$//; s/-\([0-9]\+\)$/+dev\1/')
          commit_short=$(git rev-parse --short "${commit_sha}")
          git_version_tag=$(git describe --tags --match 'v*')
          
          # extract branch name
          if [ ${{ github.event_name }} != 'pull_request' ] && [ ${{ github.event_name }} != 'pull_request_target' ]
          then
            echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
          else
            echo "::set-output name=branch_name::${GITHUB_HEAD_REF}"
          fi
          
          echo "::set-output name=images::${images}"
          echo "::set-output name=tags::${tags}"
          echo "::set-output name=labels::${labels}"
          echo "::set-output name=date::${commit_date}"
          echo "::set-output name=version::${commit_version}"
          echo "::set-output name=commit::${commit_short}"
          echo "::set-output name=cnp_version::${git_version_tag}"
      -
        name: Set GoReleaser environment
        run: |
          echo GOPATH=$(go env GOPATH) >> $GITHUB_ENV
          echo PWD=$(pwd) >> $GITHUB_ENV
      -
        name: Run GoReleaser to build kubectl-cnp plugin
        uses: goreleaser/goreleaser-action@v3
        if: |
          github.event_name == 'schedule' || github.event.inputs.build_plugin == 'true'
        with:
          distribution: goreleaser
          version: latest
          args: build -f .goreleaser.yml --skip-validate --rm-dist --id kubectl-cnp
        env:
          DATE: ${{ steps.build-meta.outputs.date }}
          COMMIT: ${{ steps.build-meta.outputs.commit }}
          VERSION: ${{ steps.build-meta.outputs.version }}
      # Send Slack notification once build including plugin kubectl-cnp fails, we only report the scheduled run to avoid message overflow
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: |
          failure() && github.event_name == 'schedule'
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/85171364?size=48
          SLACK_USERNAME: ghBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: Build plugin `kubectl-cnp` failed!
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build -f .goreleaser-multiarch.yml --skip-validate --rm-dist --id manager
        env:
          DATE: ${{ steps.build-meta.outputs.date }}
          COMMIT: ${{ steps.build-meta.outputs.commit }}
          VERSION: ${{ steps.build-meta.outputs.version }}
      -
        name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.build-meta.outputs.images }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      -
        name: Detect platforms
        id: docker-platforms
        run: |
          # Available architecture on UBI8 are: linux/amd64, linux/ppc64le, linux/s390x
          # Keep in mind that adding more platforms (architectures) will increase the building
          # time even if we use the ghcache for the building process.
          platforms="linux/amd64,linux/ppc64le,linux/s390x"
          echo "::set-output name=platforms::${platforms}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:qemu-v6.1.0
          platforms: ${{ steps.docker-platforms.outputs.platforms }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to CloudSmith.io
        uses: docker/login-action@v2
        with:
          registry: docker.cloudsmith.io
          username: ${{ secrets.CS_USER }}
          password: ${{ secrets.CS_USER_APIKEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v3.1.1
        with:
          platforms: ${{ steps.docker-platforms.outputs.platforms }}
          context: .
          push: true
          build-args: |
            VERSION=${{ steps.build-meta.outputs.version }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.build-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Image Meta
        id: image-meta
        env:
          TAGS: ${{ steps.docker-meta.outputs.tags }}
        run: |
          # If there is more than one tag, take the first one
          # TAGS could be separated by newlines or commas
          image=$(sed -n '1{s/,.*//; p}' <<< "$TAGS")
          echo "::set-output name=image::${image}"
  