name: pull_request_backport
# on:
#   pull_request_target:
#     types:
#       - closed
#       - opened
#       - reopened
#     branches:
#       - main
#   pull_request:
#     types:
#       - closed
#       - opened
#       - reopened
#     branches:
#       - main
env: 
  GLOBAL_VAR: "values"

jobs:
  # Label the source pull request with 'backport-requested' and all supported releases label, the goal is, by default
  # we backport everything
  label-source-pr:
    name: label the source pr
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-20.04
    env:
      JOB_VAR: "values"
    steps:
      -
        name: label the pull request
        uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number:  ${{ github.event.pull_request.number }}
          labels: |
            backport-requested
            release-1.16
            release-1.17
      -
        name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            By default, the pull request is supposed to backport to all release branches.
            Currently only pull request merged with one single commit is supported, if `Rebase and merge`
            is used with more than one commit, need backport manually.
          reactions: heart

  ## backport pull request in condition when pr contains 'backport-requested' label and contains target branches labels
  back-porting-pr:
    name: backport to release branches
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'backport-requested')
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        branch:
          -  release-1.16
          -  release-1.17
    env:
      JOB_VAR: "values"
      PR: ${{ github.event.pull_request.number }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Check labels
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PR: ${{ github.event.pull_request.number }}
        run: |
        
          echo "This is call the global var ${GLOBAL_VAR}"
          echo "This is call the global var without block $GLOBAL_VAR"
          echo "This is call the global var with context ${{env.GLOBAL_VAR}}"
          echo "This is call the job var ${JOB_VAR}"
          echo "This is call the job var without block $JOB_VAR"
          echo "This is call the job var with context ${{env.JOB_VAR}}"
          label=$(gh pr view ${PR} --json labels -q ".labels.[].name" 2>/dev/null | grep ${{ matrix.branch }} || :)
          if [ -z "${label}" ]
          then
            echo "No ${{ matrix.branch }} label found!"
            exit 0
          fi
          echo "LABEL=${label}" >> $GITHUB_ENV
          echo "find label ${label} in pull request ${PR}"
          commit=$(gh pr view ${PR} --json mergeCommit -q ".mergeCommit.oid" 2>/dev/null || :)
          if [ -z "${commit}" ]
          then
            echo "No commit found!"
            exit 0
          fi
          echo "COMMIT=${commit}" >> $GITHUB_ENV
          echo "cherry-pick commit ${commit} to branch ${{ matrix.branch }}"
          author_name=$(git show -s --format='%an' "${commit}")
          echo "AUTHOR_NAME=${author_name}" >> $GITHUB_ENV
          author_email=$(git show -s --format='%ae' "${commit}")
          echo "AUTHOR_EMAIL=${author_email}" >> $GITHUB_ENV
      -
        name: Configure git user
        if: |
          env.LABEL != '' &&
          env.COMMIT != '' &&
          env.LABEL == matrix.branch
        run: |
          git config user.email "${{ env.AUTHOR_EMAIL }}"
          git config user.name "${{ env.AUTHOR_NAME }}"
      -
        name: cherry pick
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          git fetch
          git checkout -B ${{ matrix.branch }} origin/${{ matrix.branch }} -t -f
          git checkout -B cherry-pick-${{ matrix.branch }}-${PR}-${{ env.COMMIT }} -f
          git cherry-pick -x --allow-empty-message --mainline 1 ${{ env.COMMIT }}
          git push origin cherry-pick-${{ matrix.branch }}-${PR}-${{ env.COMMIT }}:cherry-pick-${{ matrix.branch }}-${PR}-${{ env.COMMIT }}
      -
        name: create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        if: |
          success() &&
          env.COMMIT != ''
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: cherry-pick-${{ matrix.branch }}-${{ github.event.pull_request.number }}-${{ env.COMMIT }}
          target_branch: ${{ matrix.branch }}
          title: "chore(backport): backport pull request ${{ github.event.pull_request.number }} to branch ${{ matrix.branch }}"
          body: "This is a backport pull request, use rebase and merge to keep the original information"
          label: backport,do not squash
      -
        name: create ticket
        uses: dacbd/create-issue-action@v1.2.1
        if: |
          always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Backport failure for pull request ${{ github.event.pull_request.number }}
          labels: backport failure
          body: |
            ### Context
            Automatically backport failure

            Pull request: ${{ github.event.pull_request.number }} and ${PR} and and ${{ env.PR }}
            commit: ${{ env.COMMIT }}
            Release Branch: ${{ matrix.branch }}

